# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfb9d97d26120e1423cbacc567e37fb46dd0ee65ad724ae9e30860a0be8437e70c984fb3e7b3cd5412c2924f809572bbb06cacf54844c6ad18b2624f0ef02c23

test:
  secret_key_base: c4920e94ed39794174338f26a935c7ea1d6e1bd26bc1389629fe5890b533277861b86113c6cc4ffd7122becdf671480360a2b50284eff953cceb1b236e526d56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
